### ISSUE TITLE
Error When Passing Data to Window

### ISSUE THREAD

**Issue by 51n7** [guasam/electrovite-react#3]
Hi, when trying to send data from `main.ts` to the front end I get the (dev tools) console error: `__dirname is not defined` and the app breaks.

#### **main.ts:**
```
function createMainWindow() {
  mainWindow = new BrowserWindow({
    ...
  });

  mainWindow.webContents.send('send-data', 'test');
  
  ...
  
  return mainWindow;
}
```

#### **App.tsx:**
```
import { ipcRenderer } from 'electron';

const App = () => {

  ipcRenderer.on('send-data', function (test) {
    console.log(test);
  });

  return (
    <div>
      <h1>ElectroVite</h1>
    </div>
  );
};

export default App;
```

After a bit of searching it looks like it might be an issue with one of the `vite.*.config.ts` files but I havnt been able to figure out what the fix would be, also I could be wrong about that.

**Comment by guasam** [comment]
Hello @51n7 

By default, without setting `{nodeIntegration: true, contextIsolation: false}` for BrowserWindow instance, we can't use `IPC` calls directly in renderer process. 
(Its not recommended due to security concerns)

Safe way is to use IPC calls in preload and expose them using contextBridge : `src/renderer/preload.ts`

**Comment by 51n7** [comment]
Do you have an example using `contextBridge` with this project? I'm still failing to get this to work.

**Comment by guasam** [comment]
You can find a similar example in a different project's preload file, link below.
API for custom window titlebar events is exposed into renderer process using `contextBridge`

https://github.com/codesbiome/electron-react-webpack-typescript-2023/blob/master/misc/window/windowPreload.ts

**Comment by 51n7** [comment]
As I suspected the issues with IPC are related to typescript. I've seen various projects using an additional `preload.d.ts` with the following code to allow use of contextBridge:

#### preload.ts
```
import { contextBridge } from 'electron';

const api = {
  test: 'asd',
};

contextBridge.exposeInMainWorld('api', api);
```

#### preload.d.ts
```
export {};

declare global {
  interface Window {
    api: unknown;
  }
}
```

However it looks like the project you linked has a work-around by using `(window as any)` ([link](https://github.com/codesbiome/electron-react-webpack-typescript-2023/blob/master/misc/window/titlebarContextApi.ts)) to allow data being attached to the window in the renderer.

Unless you feel anything needs to be captured in regard to typescript and IPC's feel free to close this ticket as I understand this might not be an issue for a boilerplate project.

**Comment by 51n7** [comment]
This article was perfect for getting me up and running with Typescript and IPC's:
https://www.jsgarden.co/blog/how-to-handle-electron-ipc-events-with-typescript

Problem solved on my end 👍
